Q1:DISPLAY EMPID,EMPLOYEE_NAME,MONTHLY_SALARY,QUARTLY_SALARY,ANUAL_SALARY FOR EMPLOYEE ?
QUERY:-
=======
  SELECT EMPNO EMPID,ENAME AS EMPLOYEE_NAME , SAL AS MONTHLY_SALARY ,  SAL*3 QUARTERLY_SALARY ,  SAL*12 AS ANNUAL_SALARY
  FROM EMP;

  
  

Q2:DISPLAY EMPLOYEE_NO,EMPLOYEE_NAME,MONTHLY_SAL,COMMISSION,PF(SAL*0..12),HRA(SAL*10),OTHERS(SAL*15),
   MONTHLY_GROSS(MONTHLY_SAL+COMMISION+PF+HRA+OTHERS),CTC/ANUAL_PACKAGE(MONTHLY_GROSS*12) ?

QUERY:-
=======
    SELECT EMPNO AS EMPLOYEE_NO , ENAME AS EMPPLOYEE_NAME , SAL AS MONTHLY_SALARY , COMM AS COMMISSION , SAL*0.12 AS PF , SAL*0.10 HRA,
    SAL*0.15 AS DA , SAL+NVL(COMM,0)+SAL*0.12+SAL*0.10+SAL*0.15 AS MONTHLY_GROSS , (SAL+NVL(COMM,0)+SAL*0.12+SAL*0.10+SAL*0.15)*12 AS ANNUAL_PACKAGE
    FROM EMP;
 
 
 
 

Q3:DISPLAY EMPNO,  MERGE WITH ENAME AND JOB AND MAKE AN ALIAS WITH NAMEJOB?

QUERY:-
=======
    >SELECT EMPNO , ENAME||JOB AS NAME_JOB FROM EMP;
    > SELECT EMPNO , CONCAT(ENAME ,JOB) AS NAME_JOB FROM EMP;
 
 
 


Q4:Display unique job from emp table?

QUERY:-
=======
   SELECT  DISTINCT JOB FROM EMP;
   SELECT UNIQUE JOB FROM EMP;
 
 
 
 
Q5:DISPLAY SAL , ANNUAL_SAL WHO ARE WORKING IN DEPTNO 10 OR 30 AND WOKRING AS A SALESMAN AND THIER SALARY IS MORETHAN 1500 ?

QUERT:-
======
 SELECT ENAME, SAL , SAL*12 AS ANNUAL_SALARY FROM EMP WHERE DEPTNO IN (10,30) AND JOB='SALESMAN' AND SAL>1500;
 
 
 
 
 

Q6:DISPLAY EMPNO , ENAME, SAL AS MONTHLYSAL ,PERDAY SAL where PERDAY SAL IS MORE THAN 300?
 QUERY:-
 =========
 
  SELECT EMPNO , ENAME, SAL AS MONTHLY_SALARY , ROUND(SAL/30) PERDAY_SAL FROM EMP WHERE SAL/30>300;





Q7:Display empno,ename,sal and  annual_sal who are not getting any commission?

QUERY:-
=======

SELECT EMPNO , ENAME, SAL ,SAL*12 AS ANNUAL_SALARY ,COMM FROM EMP WHERE COMM IS NULL ;




Q8:Display empno,ename,sal,mgr and job who is not reporting to any manager?

QUERY:-
======
  SELECT EMPNO , ENAME, SAL , MGR ,JOB FROM EMP WHERE MGR IS NULL;



Q9:DISPLAY ENAME WHO GETTING ANY COMMISSION?

QUERY:-
=========
   SELECT ENAME FROM EMP WHERE COMM IS NOT NULL;


Q10:DISPLAY EMPLOYEE INFERMATION WHO GETTING  SAL MORE THAN 2000 ?

QUERY:-
========
 SELECT * FROM EMP WHERE SAL>2000;


Q11:DISPLAY EMPLOYEE INFERMATION WHO WORKING UNDER SALESMAN?

QUERY:-
==========
   SELECT * FROM EMP WHERE JOB='SALESMAN';


Q12:DISPLAY EMPLOYEE INFERMATION WHO BELONGS TO DEPTNO 30 OR 10?

QUERY:-
======
 SELECT * FROM EMP WHERE DEPTNO IN (30,10);
 


Q13:DISPLAY EMPLOYEE INFERMATION WHO DOES NOT GETTING COMMISSION ,IF THEY DID NOT ANY COMMISSION THENDISPLAY 100?

QUERY:-
======
 SELECT  COMM, NVL2(COMM,0,100) FROM EMP; 


Q14:LIST THE EMPLOYEE ENAME WITH UPPER CASE WHO ARE WORKING AS SALESMAN AND THEIR SAL RANGE IS 1000 TO 3000.
 
QUERY:-
========
   SELECT UPPER(ENAME) FROM EMP WHERE JOB='SALESMAN' AND SAL BETWEEN 1000 AND 3000 ;

 
Q15:DISPLAY EMPNO,  MERGE WITH ENAME AND  JOB  AND MAKE AN ALIAS WITH NAMEJOB AND CONVERT MERGED COLUMN  TO INITCAP.

QUERY:
======
SELECT EMPNO , INITCAP(CONCAT(ENAME , JOB )) AS NAMEJOB FROM EMP ;



Q16:MERGE AND DISPLAY EMPNO WITH JOB WHERE ENAME  CONTAINS 4 CHARCTER.

QUERY:-
=========
   SELECT CONCAT(ENAME , JOB ) FROM EMP WHERE LENGTH(ENAME)=4 ;



Q17:DISPLAY SAL , ANNUAL_SAL FOR EMPLOYEES WHO ARE WORKING IN DEPTNO 10 OR 30 AND WOKRING AS A SALESMAN AND THIER SALARY IS MORETHAN 1500 AND ENAME START''S WITH 'A'.

QUERY:-
=======

SELECT  ENAME ,SAL , SAL*12 ANNUAL_SALARY FROM EMP WHERE DEPTNO IN (10,30) AND JOB='SALESMAN' AND SAL>1500 AND SUBSTR(ENAME , 1,1)='A'
SELECT  ENAME ,SAL , SAL*12 ANNUAL_SALARY FROM EMP WHERE DEPTNO IN (10,30) AND JOB='SALESMAN' AND SAL>1500 AND ENAME LIKE 'A%';




Q18:DISPLAY CAPITAL LETTER EMPLOYEE, WHO IS JOINED IN THE YEAR 81 AND THEY HAVE 'S' WITH THIERNAME AND ORDER WITH 
DEPTNO DESC AND SALARY ASCENDING.

QUERY:-
=======
 SELECT * FROM EMP WHERE HIREDATE BETWEEN '01/JAN/81' AND  '31/DEC/81' AND INSTR(ENAME , 'S')>1 ORDER BY DEPTNO DESC,SAL ASC;




Q19:DISPLAY EMPLOYEE INFORMATION WHERE ENAME HAVE 4 CHARACTERS?

QUERY:-
======
  SELECT * FROM EMP WHERE LENGTH(ENAME)=4;



Q20: DISPLAY EMPLOYEE INFORMATION WHO IS GETTING 3 DIGIT SALARY?
 
QUERY:-
========
 SELECT * FROM EMP WHERE LENGTH(SAL)=3;
  
  
  

Q21: DISPLAY EMPLOYEE INFORMATION WITH SORTING OF LENGTH OF THEIR ENAME?

QUERY:-
=======
 SELECT * FROM EMP ORDER BY LENGTH(ENAME);



Q22: DISPLAY STARTING CHARACTER TO FIRST A  IN NARAYAN?

QUERY:-
========
   SELECT SUBSTR('NARAYAN' , 1, INSTR('NARAYAN','A')) FROM DUAL;
   SELECT SUBSTR('NARAYAN' , 1, INSTR('NARAYAN','A',1,2)) FROM DUAL;




Q23:DISPLAY STARTING CHARACTER TO LAST A  IN NARAYAN?

SELECT SUBSTR('NARAYAN' , 1 , INSTR( 'NARAYAN' , 'A',-1)) FROM DUAL;
SELECT SUBSTR('NARAYAN' , 1 , INSTR( 'NARAYAN' , 'A',1,3)) FROM DUAL;




Q24: DISPLAY STARTING CHARACTER TO I IN ENAME?

QUERY:-
=========
SELECT SUBSTR(ENAME , 1 , INSTR(ENAME , 'I')) FROM EMP;


Q26:MERGE AND DISPLAY EMPNO WITH JOB WHOS ENAME CONTAINS 4 CHARACTER.

QUERY:-
========
SELECT CONCAT(EMPNO,JOB) FROM EMP WHERE LENGTH(ENAME)=4;

Q27:DISPLAY EMPLOYEES INFORMATION WHOSE SECOND or THIRD LETTER OF ENAME CONTAINS D?

QUERY:-
=======
  SELECT * FROM EMP WHERE SUBSTR(ENAME ,2, 1)='D'  OR SUBSTR(ENAME , 3,1)='D' ;

  SELECT * FROM EMP WHERE ENAME LIKE '_D%' OR ENAME LIKE '__D%' ;




Q28:DISPLAY CAPITAL LETTER EMPLOYEE, WHO IS JOINED IN THE YEAR 81 AND THEY HAVE 'S' WITH THIERNAME AND ORDER WITH DEPTNO DESC AND SALARY ASCENDING.
 
 QUERY:-
 ========
  SELECT * FROM EMP WHERE HIREDATE BETWEEN '01/JAN/81' AND '31/DEC/81' AND INSTR(ENAME , 'S')>1 ORDER BY DEPTNO DESC , SAL;
  
 
 
 
Q29: DISPLAY EMPLOYEE INFORMATION WHOSE SAL IS GREATER THAN 2000 AND THEY HAVE COMMISSION AND THEN REPORTING TO MGR.

QUERY:-
=========

SELECT * FROM EMP WHERE SAL>2000 AND COMM IS NOT NULL AND MGR IS NOT NULL;

Q30: DISPLAY EMPNO,ENAME,COMM(IF COMMISSION IS NULL THEN DISPLAY 1000, IF COMM IS NOT NULL THEN DISPLAY 2000).

QUERY:-
=======
 SELECT EMPNO , ENAME ,COMM, NVL2(COMM , 2000 , 1000) FROM EMP;
  
  
  
  

Q31: DISPLAY EMPLOYEE INFORMATION WHOSE EMPLOYEE NAME HAVING 4 CHARACTERS & THEY CONTAINS 'I' IN THEIR NAME.

QUERY:-
========
  SELECT * FROM EMP WHERE LENGTH(ENAME)=4 AND INSTR(ENAME , 'I')>1 ;
  SELECT * FROM EMP WHERE LENGTH(ENAME)=4 AND ENAME LIKE '%I%';



Q32: COMBINE 1ST TWO CHARACTER OF ENAME & LAST TWO CHARACTER OF ENAME.

QUERY:-
=======
 SELECT  ENAME , SUBSTR(ENAME , 1,2) ||SUBSTR(ENAME,-2) FROM EMP;
 SELECT ENAME , SUBSTR(ENAME,1,2) || SUBSTR(ENAME , LENGTH(ENAME)-1,2) FROM EMP;



Q33: DISPLAY EMPLOYEE INFORMATION WHERE ANNUAL SALARY IS GREATER THAN 50000.
 QUERY:-
 =========
 SELECT * FROM EMP WHERE SAL*12 >50000;
 
 



Q34: DISPLAY EMPLOYEE INFORMATION WHERE LENGTH(ENAME) IS 4 OR 5 OR 6.

QUERY:-
========
SELECT * FROM EMP WHERE LENGTH(ENAME) IN (4,5,6);
SELECT * FROM EMP WHERE LENGTH(ENAME) BETWEEN 4 AND 6;



Q35: DISPLAY EMPNO,ENAME,ANNUALSAL WITH DESCENDING ORDER OF ANNUALSAL.

QUERY:-
========
 SELECT EMPNO, ENAME , SAL*12 AS ANNUAL_SALARY FROM EMP  ORDER BY  ANNUAL_SALARY DESC;




Q36:DISPLAY 1ST TWO CHARACTER OF EMPNO WITH ENAME(MERGE WITH '-').

QUERY:-
========

SELECT SUBSTR(ENAME , 1,1)||'-'||SUBSTR(ENAME , 2,1) FROM EMP;



Q37:DISPLAY EMPLOYEE INFORMATION WHERE 3RD CHARACTER OF ENAME IS 'I'.

QUERY:-
========
 SELECT * FROM EMP WHERE SUBSTR(ENAME , 3,1)='I' ;



Q38:DISPLAY EMPNO,ENAME,ANNUAL SALARY,HALF YEARLY SALARY WHO ARE GETTING COMMISSION.

QUERY:-
=======
SELECT EMPNO ,ENAME , COMM, SAL*12 AS ANNUAL_SALARY , SAL*6 AS HAFLYEARLY_SALARY FROM EMP WHERE COMM IS NOT NULL;


Q39:DISPLAY EMPLOYEE INFORMATION WHO ARE EARNING SALARY IN 3 DIGITS.

QUERY:-
=======
 SELECT * FROM EMP WHERE LENGTH(SAL)=3;




Q40:DISPLAY 1ST CHARACTER OF ENAME MERGE WITH LAST CHARACTER OF ENAME.
  
  QUERY:-
  =========
    SELECT SUBSTR(ENAME , 1,1) || SUBSTR(ENAME , LENGTH(ENAME)) FROM EMP ;
  
   
   


Q41:display employeename where ename contains o with out using like operator?

QUERY:-
========
 SELECT ENAME AS EMPLOYEE_NAME FROM EMP WHERE INSTR(ENAME , 'O')>1 ;
 
 



Q42:Write an SQL query to display the firstname and lastname in 2 different columns.if last name not present display with oracle

QUERY:-
=========
   SELECT ENAME AS FIRSTS_NAME , ENAME AS LAST_NAME, NVL(ENAME , 'ORACLE') FROM EMP;
   
   
Q44: Display unique Jobs from EMP table. 

QUERY:-
============
SELECT UNIQUE JOB FROM EMP;

SELECT  DISTINCT JOB FROM EMP;



Q45: Display the details of all MANAGERS.

QUERY:--
=======
SELECT * FROM EMP WHERE JOB='MANAGER';


Q46: LIst the emps who joined before 1981.
 
 QUERY:-
 ========
   SELECT * FROM EMP WHERE HIREDATE <'31/DEC/81';
 
 
 
 
Q47: Display the Empno, Ename, Job, Hiredate, and experience of all Managers.
 
 QUERY:-
 =======
  SELECT EMPNO , ENAME, JOB , HIREDATE , ROUND((SYSDATE - HIREDATE)/365) AS EXPERIENCE_IN_YEAR FROM EMP WHERE JOB='MANAGER';
   SELECT EMPNO , ENAME, JOB , HIREDATE  ,ROUND( (SYSDATE - HIREDATE)/30) AS EXPERIENCE_IN_MONTHS FROM EMP WHERE JOB='MANAGER';

 
 
 
Q48: List the Empno, Ename, Sal, Exp of all emps working for Mgr 7639.
 
 QUERY:-
 =========
 SELECT EMPNO , ENAME , SAL ,MGR ,  ROUND(SYSDATE - HIREDATE)/365  FROM EMP WHERE MGR =7698;
  SELECT EMPNO , ENAME , SAL ,MGR , ROUND((SYSDATE - HIREDATE)/365)  FROM EMP WHERE MGR =7698;



Q49: Display all the details of the emps whose Comm. Is more than their Sal. 

QUERY:-
==========

SELECT * FROM EMP WHERE COMM>SAL;



Q50:List the emps along with their Exp and whose Daily Sal is more than Rs. 100.
 
 QUERY:-
 =========
   SELECT ENAME , SAL , ROUND(SAL/30) AS DAILY_SALARY ,ROUND( (SYSDATE - HIREDATE )/365) AS EXP  FROM  EMP
   WHERE ROUND(SAL/30) >100.
 
 SELECT ROUND( SAL/30) FROM EMP;
 
 
Q51: List the emps who are working for the Deptno 10 or 20. 

QUERY:-
=======
SELECT * FROM EMP WHERE DEPTNO IN (10,20);




Q52: List the emps who are working under any Manager.

QUERY:-
=======
SELECT * FROM EMP WHERE JOB='MANAGER';


 
Q53: List all the Clerks of Deptno 20.
 
 QUERY:-
 ======
  SELECT * FROM EMP WHERE JOB='CLERK' AND DEPTNO=20;
 
 
 
 
Q54: Display the details of SMITH.   

QUERY:-
======
  SELECT * FROM EMP WHERE ENAME='SMITH';
  


  